apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: summer-trip
  name: summer-trip-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: summer_trip
  template:
    metadata:
      labels:
        app: summer_trip
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: summer_trip
        image: gcr.io/loony-argocd/summer-trip-v1
        imagePullPolicy: Always
		 	 	
